export const data={
    name:"root",
    isFolder:true,
    children:[
        {
            name:"src",
            isFolder:true,
            children:[
                {
                    name:"App.css",
                    isFolder:false,
                    children:[]
                },
                {
                    name:"App.jsx",
                    isFolder:false,
                    children:[]
                },
                {
                    name:"index.css",
                    isFolder:false,
                    children:[]
                },
                {
                    name:"index.jsx",
                    isFolder:false,
                    children:[]
                }
            ]
        },
          {
        name:'public',
        isFolder: true,
        children: [
            {
                name:'index.html',
                isFolder:false,
                children:[]
            },
            {
                name:"index.css",
                isFolder:false,
                children:[]
            }
        ]
    },
    {
        name:'package.json',
        isFolder:false,
        children:[]
    }
    ],
  
}